### PR TITLE
Fix findByToken

### PR DESCRIPTION
**Pull request by Itsyuka**
Expects a user object if found

### CODE REVIEW

**Comment by juampi92** [comment]
The token method returns the uid already populated. IDK if that's faster or what, but we'd need to remove the populate on the fetchSession method

````javascript
return this.findOneAndUpdate({
  token,
  type,
  expires: {
    $gte: moment()
  }
}, {
  expires: moment().add(5, 'days')
}).populate('uid', '_id name').exec()
````

**Comment by juampi92** [comment]
I think that the way it is is good cause you can config what you get of the user modifying the token's fetchSession. You can select just some properties from the user and not the full object

**Comment by Itsyuka** [comment]
Ah yes, very true. I should of looked into it a bit more.

**Comment by juampi92** [comment]
But I made that token myself! haha no worries, I'm also new to Adonis.
I was trying to make a parent class for the User that contains the static property "primaryKey" (that is required by the Auth Scheme) but I couldn't figure out how, so I just added ` UserSchema.statics.primaryKey = '_id' ` on the user, but I'd be cool if the BaseModel contained that or something...

**Comment by Itsyuka** [comment]
Ah that, to pull a static item you would need to pull it as
`Base.primaryKey` instead of `this.primaryKey`

**Comment by Itsyuka** [comment]
Take a look at this commit to if you don't quite understand https://github.com/Itsyuka/adonis-mongoose-model/commit/b7bb72e7a1350cc22ab18e7f50ba4acc05c0e0c2

Edit: Lack of sleep, jumbling what I'm reading

**Comment by juampi92** [comment]
Commit not found.
But when I add static properties to the mongoose "loadClass", he looses the static properties, IDK why

**Comment by Itsyuka** [comment]
I made a mistake when reading code due to my lack of sleep.
But you can only pull static properties from the base object, not an instance of the object.
So to get the primary key from an instance, you would need to make a
`get primaryKey () { return Base.primaryKey }`
or
`get primaryKey () { return this.constructor.primaryKey }`

**Comment by Itsyuka** [comment]
This is what I know from doing a few things recently, this should work with mongoose's loadClass function, but I could be entirely wrong

```javascript
'use strict'

class Base {
  static get primaryKey () { // Static getter for the primaryKey
    return '_id'
  }

  get primaryKey () { // Gets the static getter for primaryKey that can be used in an instance of Model
    return Base.primaryKey
  }

  get primaryKeyValue () {
    return this[Base.primaryKey] // Returns the primaryKey value in an instance
  }
}

module.exports = Base
```

**Comment by juampi92** [comment]
Yeah, that static get was my first approach, but test it, mongoose does not inherit that static property. It ignores it completely when we use loadClass... It's a bummer

**Comment by Itsyuka** [comment]
Solved it, mongoose doesn't allow static getters, but does allow the function. So where you have `_Model.primaryKey` or `_Model.primaryKey()` it can now be `_Model.getPrimaryKey()` and should return it fine

```javascript
'use strict'

class Base {
  static get primaryKey () { // Static getter for the primaryKey
    return '_id'
  }

  static getPrimaryKey() {
    return Base.primaryKey
  }

  get primaryKey () { // Gets the static getter for primaryKey that can be used in an instance of Model
    return Base.getPrimaryKey()
  }

  get primaryKeyValue () {
    return this[Base.getPrimaryKey()] // Returns the primaryKey value in an instance
  }
}

module.exports = Base
```

**Comment by juampi92** [comment]
Yes, I know, that's what I did at first, BUT, I cant change the Auth Scheme, and the Auth Scheme uses the static property... :/
So unless we adapt to the same exact syntax, it's no use.... :(

Check this code:
https://github.com/adonisjs/adonis-auth/blob/develop/src/Schemes/Api.js#L95

**Comment by Itsyuka** [comment]
Works fine for me

**Comment by juampi92** [comment]
Ok, I'll test it out tomorrow and add it to the code, thanks. 🙂

**Comment by Itsyuka** [comment]
I'll do a pull and you can try it out

**Pull request closed without merging**
